version: "3"
services:
  scrape:
    image: openstates/openstates
    environment:
    - BILLY_MONGO_HOST=database
    - MYSQL_HOST=mysql
    - NEW_YORK_API_KEY
    - INDIANA_API_KEY
    - PUPA_ARGS
    volumes:
    - .:/opt/openstates/openstates/
    depends_on:
    - database
    entrypoint: /opt/openstates/openstates/pupa-scrape.sh
  openstates.org:
    image: openstates/openstates.org
    command: python manage.py runserver 0.0.0.0:8000
    environment:
    - MONGO_HOST=database
    ports:
    - "8000:8000"
    depends_on:
    - database
  database:
    image: mongo
    ports:
    - "27017:27017"
  mysql:
    image: mysql
    ports:
    - "3306:3306"
    environment:
    - MYSQL_DATABASE=capublic
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  ca-download:
    image: govhawk/openstates:debug-ca-0
    entrypoint: /opt/openstates/openstates/openstates/ca/download.sh
    environment:
    - MYSQL_USER=scraper
    - MYSQL_PASSWORD=A7iJTM7rTmVXK79
    - MYSQL_HOST=158.69.86.15
    volumes:
    - .:/opt/openstates/openstates/
    # depends_on:
    # - mysql
